---
resources:
  - ../../base
  - distributed-workloads.yaml
  - namespace.yaml
  - llama-cpp-runtime-template.yaml
#  - serving-llama31-cpp.yaml
#  - serving-llama32-cpp.yaml
#  - serving-llama32-vllm.yaml
   - serving-health-finetune-vllm.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: dsc-cr.yaml
  - path: odh-dashboard.yaml
