---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    enable-route: 'true'
    opendatahub.io/accelerator-name: nvidia-gpu
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe
    opendatahub.io/template-name: vllm-runtime
    openshift.io/display-name: sno-llama32-vllm
  labels:
    opendatahub.io/dashboard: "true"
  name: sno-llama32-vllm
  namespace: llama-serving
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
        - --port=8080
        - --model=/mnt/models/Llama-3.2-3B-Instruct-Q8_0.gguf
        - --quantization=gguf
        - --max-model-len=131072
        - --enforce-eager
        - --enable-auto-tool-choice
        - --tool-call-parser llama3_json
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: quay.io/modh/vllm:rhoai-2.17-cuda  # quay.io/eformat/vllm:latest  # quay.io/modh/vllm:rhoai-2.13
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: sno-llama32-vllm
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    serving.kserve.io/deploymentMode: Serverless
  labels:
    opendatahub.io/dashboard: "true"
  name: sno-llama32-vllm
  namespace: llama-serving
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 600000
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      runtime: sno-llama32-vllm
      storage:
        key: connection-minio
        path: Llama-3.2-3B-Instruct-Q8_0.gguf
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
