---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    enable-route: 'true'
    opendatahub.io/accelerator-name: nvidia-gpu
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe
    opendatahub.io/template-name: vllm-runtime
    openshift.io/display-name: health-finetune
  labels:
    opendatahub.io/dashboard: "true"
  name: health-finetune
  namespace: llama-serving
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
        - --port=8080
        - --model=/mnt/models
        - --served-model-name=mhepburn-health-care-031325
        - --max_model_len=7184
        - --chat-template=/app/data/template/tool_chat_template_granite.jinja
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: quay.io/eformat/vllm:latest  # quay.io/modh/vllm:rhoai-2.17-cuda quay.io/modh/vllm:rhoai-2.13
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: health-finetune
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    serving.kserve.io/deploymentMode: Serverless
  labels:
    opendatahub.io/dashboard: "true"
  name: health-finetune
  namespace: llama-serving
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 600000
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      runtime: health-finetune
      storage:
        key: connection-minio
        path: mhepburn-health-care-031325
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
