---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-configure
  labels:
    app.kubernetes.io/name: minio
spec:
  template:
    metadata:
      name: minio-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "mc --config-dir=/tmp config host add local http://minio:9000 minio minio1234 && mc --config-dir=/tmp mb --ignore-existing local/data/ && mc --config-dir=/tmp mb --ignore-existing local/models/"
  backoffLimit: 25
