---
apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  finalizers:
  - cert-manager-operator.operator.openshift.io/cert-manager-webhook-deployment
  - cert-manager-operator.operator.openshift.io/cert-manager-controller-deployment
  - cert-manager-operator.operator.openshift.io/cert-manager-cainjector-deployment
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  unsupportedConfigOverrides: null
  controllerConfig:
    overrideArgs:
      - '--dns01-recursive-nameservers-only'
      - '--dns01-recursive-nameservers=1.1.1.1:53' 
