---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perf-enhancements
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/eformat/sno-llama.git
    path: gitops/applications/perf-enhancements
    targetRevision: main
    plugin:
      name: argocd-vault-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
