# 2024.1
FROM quay.io/modh/cuda-notebooks@sha256:3beed917f90b12239d57cf49c864c6249236c8ffcafcc7eb06b0b55272ef5b55
ARG ILAB_VERSION=0.18.4
USER root
RUN dnf -y install https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/n/nvtop-3.1.0-2.el9.x86_64.rpm
RUN dnf -y install python3.11 python3.11-devel python3.11-pip
RUN sed -i -e "s|/opt/app-root/bin/python3.9|/usr/bin/python3.11|" /opt/app-root/bin/pip3.11
RUN CMAKE_ARGS="-DLLAMA_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=all-major" FORCE_CMAKE=1 pip3.11 install --verbose torch==2.3.1 git+https://github.com/instructlab/instructlab.git@v${ILAB_VERSION} --no-cache-dir --force
RUN rm -rf /var/cache/dnf
USER 1001
