---
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  components:
    codeflare:
      managementState: Managed
    dashboard:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    kserve:
      managementState: Managed
    kueue:
      managementState: Managed
    modelmeshserving:
      managementState: Managed
    # modelregistry:
    #  managementState: Managed
    ray:
      managementState: Managed
    # trainingoperator:
    #   managementState: Managed
    # trustyai:
    #   managementState: Managed
    workbenches:
      managementState: Managed
