---
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  namespace: redhat-ods-operator
spec:
  components:
    codeflare:
      managementState: Managed
    dashboard:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    kserve:
      managementState: Managed
      serving:
      ingressGateway:
        certificate:
          type: SelfSigned
      name: knative-serving
    kueue:
      managementState: Managed
    modelmeshserving:
      managementState: Managed
    # modelregistry:
    #  managementState: Managed
    ray:
      managementState: Managed
    # trainingoperator:
    #   managementState: Managed
    # trustyai:
    #   managementState: Managed
    workbenches:
      managementState: Managed
