---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/eformat/sno-llama.git
    path: gitops/applications/rhoai/overlay/demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - Validate=true
  ignoreDifferences:
  - group: "*"
    kind: "Route"
    managedFieldsManagers:
    - manager
    - kube-controller-manager
