---
namespace: dev-red-rag

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: chatbot
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: chatbot
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: chatbot
                image: quay.io/eformat/chatbot:latest
