---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-db
  labels:
    app.kubernetes.io/name: chatbot
spec:
  template:
    metadata:
      name: load-db
    spec:
      restartPolicy: OnFailure
      containers:
        - name: load
          image: quay.io/eformat/rag-postgres-data:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PGPASSWORD
              value: password
            - name: PROJECT
              value: quarkus-rag
          command:
            - /bin/bash
            - -c
            - |
              STATUS=$(pg_isready -h postgres -p 5432 -d vectordb -U postgres)
              until [ "$STATUS" == "postgres:5432 - accepting connections" ]
              do 
                echo "waiting for postgres connection..."
                sleep 5
                STATUS=$(pg_isready -q -h postgres -p 5432 -d vectordb -U postgres)
              done
              set -x
              psql -h postgres -p 5432 -d vectordb -U postgres -c "CREATE EXTENSION vector;"
              STATUS=$(psql -h postgres -p 5432 -d vectordb -U postgres -c "CREATE EXTENSION vector;" 2>&1)
              if [ "$STATUS" == "ERROR: extension "vector" already exists" ]; then
                echo "tables already exist - exiting OK"
                exit 0
              fi
              pg_restore -h postgres -p 5432 -d vectordb -U postgres -v /${PROJECT}/langchain_pg_collection.dmp
              pg_restore -h postgres -p 5432 -d vectordb -U postgres -v /${PROJECT}/langchain_pg_embedding.dmp
