---
namespace: dev-images-red-rag

resources:
  - ../../../base
  - pvc.yaml
  - load-db-job.yaml

patches:
  - target:
      kind: Deployment
      name: chatbot
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: chatbot
      spec:
        replicas: 1
        template:
          spec:
            initContainers:
              - command:
                  - cp
                  - '-n'
                  - /dev-images-red-rag/images-all.tar.gz
                  - /opt/app-root/src/images/images-all.tar.gz
                image: quay.io/eformat/rag-postgres-data:latest
                imagePullPolicy: Always
                name: copy-images
                volumeMounts:
                - mountPath: /opt/app-root/src/images
                  name: images
              - command:
                  - tar
                  - 'xzvf'
                  - images/images-all.tar.gz
                  - '-C'
                  - /opt/app-root/src'
                image: quay.io/eformat/chatbot-images:latest
                imagePullPolicy: IfNotPresent
                name: extract-images
                volumeMounts:
                - mountPath: /opt/app-root/src/images
                  name: images
            containers:
              - name: chatbot
                image: quay.io/eformat/chatbot-images:latest
                volumeMounts:
                - mountPath: /opt/app-root/src/images
                  name: images
            volumes:
            - name: images
              persistentVolumeClaim:
                claimName: images
