FROM quay.io/modh/vllm:rhoai-2.17-cuda
USER root
RUN microdnf -y install dnf
RUN dnf -y install https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/n/nvtop-3.1.0-2.el9.x86_64.rpm
# https://github.com/vllm-project/vllm/issues/7978 transformers-4.45.0.dev0
#RUN --mount=type=cache,target=/root/.cache/pip \
#    python3 -m pip install git+https://github.com/huggingface/transformers
# https://issues.redhat.com/browse/RHOAIENG-12238
# --chat-template /workspace/templates/template_chatml.jinja \
#COPY tokenization_utils_fast.py /opt/vllm/lib64/python3.11/site-packages/transformers/tokenization_utils_fast.py
USER 2000
